/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update it's content execute "npm run update"
 */
'use strict'

module.exports = {
  rules: {
    'vue/attribute-hyphenation': require('./rules/vue/attribute-hyphenation'),
    'vue/attributes-order': require('./rules/vue/attributes-order'),
    'vue/comment-directive': require('./rules/vue/comment-directive'),
    'vue/html-closing-bracket-newline': require('./rules/vue/html-closing-bracket-newline'),
    'vue/html-closing-bracket-spacing': require('./rules/vue/html-closing-bracket-spacing'),
    'vue/html-end-tags': require('./rules/vue/html-end-tags'),
    'vue/html-indent': require('./rules/vue/html-indent'),
    'vue/html-quotes': require('./rules/vue/html-quotes'),
    'vue/html-self-closing': require('./rules/vue/html-self-closing'),
    'vue/jsx-uses-vars': require('./rules/vue/jsx-uses-vars'),
    'vue/max-attributes-per-line': require('./rules/vue/max-attributes-per-line'),
    'vue/mustache-interpolation-spacing': require('./rules/vue/mustache-interpolation-spacing'),
    'vue/name-property-casing': require('./rules/vue/name-property-casing'),
    'vue/no-async-in-computed-properties': require('./rules/vue/no-async-in-computed-properties'),
    'vue/no-confusing-v-for-v-if': require('./rules/vue/no-confusing-v-for-v-if'),
    'vue/no-document': require('./rules/vue/no-document'),
    'vue/no-dupe-keys': require('./rules/vue/no-dupe-keys'),
    'vue/no-duplicate-attributes': require('./rules/vue/no-duplicate-attributes'),
    'vue/no-global': require('./rules/vue/no-global'),
    'vue/no-multi-spaces': require('./rules/vue/no-multi-spaces'),
    'vue/no-parsing-error': require('./rules/vue/no-parsing-error'),
    'vue/no-reserved-keys': require('./rules/vue/no-reserved-keys'),
    'vue/no-shared-component-data': require('./rules/vue/no-shared-component-data'),
    'vue/no-side-effects-in-computed-properties': require('./rules/vue/no-side-effects-in-computed-properties'),
    'vue/no-style-display': require('./rules/vue/no-style-display'),
    'vue/no-style-float': require('./rules/vue/no-style-float'),
    'vue/no-style-z-index': require('./rules/vue/no-style-z-index'),
    'vue/no-template-key': require('./rules/vue/no-template-key'),
    'vue/no-textarea-mustache': require('./rules/vue/no-textarea-mustache'),
    'vue/no-unused-vars': require('./rules/vue/no-unused-vars'),
    'vue/no-v-cloak': require('./rules/vue/no-v-cloak'),
    'vue/no-v-html': require('./rules/vue/no-v-html'),
    'vue/no-v-show': require('./rules/vue/no-v-show'),
    'vue/no-window': require('./rules/vue/no-window'),
    'vue/order-in-components': require('./rules/vue/order-in-components'),
    'vue/prop-name-casing': require('./rules/vue/prop-name-casing'),
    'vue/require-component-is': require('./rules/vue/require-component-is'),
    'vue/require-default-prop': require('./rules/vue/require-default-prop'),
    'vue/require-prop-types': require('./rules/vue/require-prop-types'),
    'vue/require-render-return': require('./rules/vue/require-render-return'),
    'vue/require-v-for-key': require('./rules/vue/require-v-for-key'),
    'vue/require-valid-default-prop': require('./rules/vue/require-valid-default-prop'),
    'vue/return-in-computed-property': require('./rules/vue/return-in-computed-property'),
    'vue/script-indent': require('./rules/vue/script-indent'),
    'vue/this-in-template': require('./rules/vue/this-in-template'),
    'vue/v-bind-style': require('./rules/vue/v-bind-style'),
    'vue/v-on-style': require('./rules/vue/v-on-style'),
    'vue/valid-cell-component': require('./rules/vue/valid-cell-component'),
    'vue/valid-image-component': require('./rules/vue/valid-image-component'),
    'vue/valid-indicator-component': require('./rules/vue/valid-indicator-component'),
    'vue/valid-input-component': require('./rules/vue/valid-input-component'),
    'vue/valid-list-component': require('./rules/vue/valid-list-component'),
    'vue/valid-picker-module': require('./rules/vue/valid-picker-module'),
    'vue/valid-scroller-component': require('./rules/vue/valid-scroller-component'),
    'vue/valid-style-flex': require('./rules/vue/valid-style-flex'),
    'vue/valid-style-font-family': require('./rules/vue/valid-style-font-family'),
    'vue/valid-style-selector': require('./rules/vue/valid-style-selector'),
    'vue/valid-switch-component': require('./rules/vue/valid-switch-component'),
    'vue/valid-template-root': require('./rules/vue/valid-template-root'),
    'vue/valid-text-component': require('./rules/vue/valid-text-component'),
    'vue/valid-textarea-component': require('./rules/vue/valid-textarea-component'),
    'vue/valid-v-bind': require('./rules/vue/valid-v-bind'),
    'vue/valid-v-else-if': require('./rules/vue/valid-v-else-if'),
    'vue/valid-v-else': require('./rules/vue/valid-v-else'),
    'vue/valid-v-for': require('./rules/vue/valid-v-for'),
    'vue/valid-v-if': require('./rules/vue/valid-v-if'),
    'vue/valid-v-model': require('./rules/vue/valid-v-model'),
    'vue/valid-v-on': require('./rules/vue/valid-v-on'),
    'vue/valid-v-once': require('./rules/vue/valid-v-once'),
    'vue/valid-v-pre': require('./rules/vue/valid-v-pre'),
    'vue/valid-v-text': require('./rules/vue/valid-v-text'),
    'vue/valid-video-component': require('./rules/vue/valid-video-component'),
    'vue/valid-web-component': require('./rules/vue/valid-web-component')
  },
  configs: {
    'base': require('./configs/base'),
    'essential': require('./configs/essential'),
    'strongly-recommended': require('./configs/strongly-recommended'),
    'recommended': require('./configs/recommended')
  },
  processors: {
    '.vue': require('./processor')
  }
}
