/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update it's content execute "npm run update"
 */
module.exports = {
  extends: require.resolve('./base'),
  rules: {
    'weex/vue/no-async-in-computed-properties': 'error',
    'weex/vue/no-document': 'error',
    'weex/vue/no-dupe-keys': 'error',
    'weex/vue/no-duplicate-attributes': 'error',
    'weex/vue/no-global': 'error',
    'weex/vue/no-parsing-error': 'error',
    'weex/vue/no-reserved-keys': 'error',
    'weex/vue/no-shared-component-data': 'error',
    'weex/vue/no-side-effects-in-computed-properties': 'error',
    'weex/vue/no-style-display': 'error',
    'weex/vue/no-style-float': 'error',
    'weex/vue/no-style-z-index': 'error',
    'weex/vue/no-template-key': 'error',
    'weex/vue/no-textarea-mustache': 'error',
    'weex/vue/no-unused-vars': 'error',
    'weex/vue/no-v-cloak': 'error',
    'weex/vue/no-v-html': 'error',
    'weex/vue/no-v-show': 'error',
    'weex/vue/no-window': 'error',
    'weex/vue/require-component-is': 'error',
    'weex/vue/require-render-return': 'error',
    'weex/vue/require-v-for-key': 'error',
    'weex/vue/require-valid-default-prop': 'error',
    'weex/vue/return-in-computed-property': 'error',
    'weex/vue/valid-cell-component': 'error',
    'weex/vue/valid-image-component': 'error',
    'weex/vue/valid-indicator-component': 'error',
    'weex/vue/valid-input-component': 'error',
    'weex/vue/valid-list-component': 'error',
    'weex/vue/valid-picker-module': 'error',
    'weex/vue/valid-scroller-component': 'error',
    'weex/vue/valid-style-flex': 'error',
    'weex/vue/valid-style-font-family': 'error',
    'weex/vue/valid-style-selector': 'error',
    'weex/vue/valid-switch-component': 'error',
    'weex/vue/valid-template-root': 'error',
    'weex/vue/valid-text-component': 'error',
    'weex/vue/valid-textarea-component': 'error',
    'weex/vue/valid-v-bind': 'error',
    'weex/vue/valid-v-cloak': 'error',
    'weex/vue/valid-v-else-if': 'error',
    'weex/vue/valid-v-else': 'error',
    'weex/vue/valid-v-for': 'error',
    'weex/vue/valid-v-html': 'error',
    'weex/vue/valid-v-if': 'error',
    'weex/vue/valid-v-model': 'error',
    'weex/vue/valid-v-on': 'error',
    'weex/vue/valid-v-once': 'error',
    'weex/vue/valid-v-pre': 'error',
    'weex/vue/valid-v-show': 'error',
    'weex/vue/valid-v-text': 'error',
    'weex/vue/valid-video-component': 'error',
    'weex/vue/valid-web-component': 'error'
  }
}
